name: Birthday Bot

on:
  # Daily at 2:00 PM CST (UTC-6 → 20:00 UTC)
  schedule:
    - cron: "0 20 * * *"
  # Manual trigger for testing
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run birthday bot
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          TEST_MODE: "false"    # if your script supports it
        run: python birthday_bot.py
        # ⬆ If your script file is named test_bot.py, change to:
        # run: python test_bot.py
  
